// Central list of what counts as "AI" for AIBlockle.
//
// Three lists, applied at different layers:
//   1. BLOCKED_DOMAINS   -> network requests to these hosts are refused (site won't load).
//   2. AI_KEYWORDS       -> used by the DOM filter to hide AI widgets/elements on pages.
//   3. AI_ELEMENT_HINTS  -> attribute/class/id fragments that usually mark an AI widget.
//
// Blocking "all AI" perfectly is impossible (AI-generated text looks like normal
// text, and server-side AI is invisible). This list targets known AI *tools,
// services, and on-page features* — the parts that are actually detectable.

// Known AI services + AI API endpoints. Matched against the request hostname:
// an entry blocks the exact host and any subdomain of it.
const BLOCKED_DOMAINS = [
  // Chat assistants / general AI
  'chatgpt.com',
  'chat.openai.com',
  'openai.com',
  'oaistatic.com',
  'oaiusercontent.com',
  'claude.ai',
  'anthropic.com',
  'gemini.google.com',
  'bard.google.com',
  'aistudio.google.com',
  'copilot.microsoft.com',
  'copilot.cloud.microsoft',
  'perplexity.ai',
  'pplx.ai',
  'poe.com',
  'character.ai',
  'you.com',
  'phind.com',
  'deepseek.com',
  'chat.deepseek.com',
  'x.ai',
  'grok.com',
  'grok.x.com',
  'mistral.ai',
  'chat.mistral.ai',
  'huggingface.co',
  'meta.ai',
  'pi.ai',
  'jasper.ai',
  'writesonic.com',
  'copy.ai',
  'quillbot.com',

  // AI image / video / audio generators
  'midjourney.com',
  'stability.ai',
  'clipdrop.co',
  'leonardo.ai',
  'runwayml.com',
  'elevenlabs.io',
  'suno.com',
  'suno.ai',
  'udio.com',
  'kling.ai',
  'pika.art',
  'ideogram.ai',
  'krea.ai',
  'civitai.com',

  // AI coding assistants
  'github.com/features/copilot',
  'githubcopilot.com',
  'cursor.com',
  'cursor.sh',
  'codeium.com',
  'tabnine.com',

  // AI API endpoints (block requests other sites make to power AI features)
  'api.openai.com',
  'api.anthropic.com',
  'generativelanguage.googleapis.com',
  'api.x.ai',
  'api.mistral.ai',
  'api.perplexity.ai',
  'api.cohere.ai',
  'api.cohere.com',
  'api.together.xyz',
  'api.groq.com',
  'openrouter.ai',
  'api.replicate.com',
  'inference.huggingface.co',
];

// Words/phrases that, when they label a button or panel, mark it as an AI feature.
// Used by the DOM filter for text/aria matching. Kept fairly specific to avoid
// hiding legitimate content that merely mentions AI.
const AI_KEYWORDS = [
  'ai overview',
  'ai-generated',
  'ai generated',
  'generated by ai',
  'ask ai',
  'ask copilot',
  'ai assistant',
  'ai chat',
  'chat with ai',
  'ai summary',
  'summarize with ai',
  'ai answer',
  'powered by ai',
  'ai suggestions',
  'copilot',
  'gemini',
  'chatgpt',
];

// Substrings found in class names, ids, data-attributes, or aria labels that
// typically indicate an AI widget/container. Matched case-insensitively.
const AI_ELEMENT_HINTS = [
  'ai-overview',
  'ai-assistant',
  'ai-chat',
  'ai-widget',
  'ai-summary',
  'ai-answer',
  'ask-ai',
  'copilot',
  'chatbot',
  'gen-ai',
  'genai',
];

module.exports = { BLOCKED_DOMAINS, AI_KEYWORDS, AI_ELEMENT_HINTS };
