// Offline test of the filter — no network needed.
const assert = require('assert');
const { filterHtml, isBlockedSite, isSafeTarget, isAiMediaHost } = require('./server');

const base = 'https://news.example.com/story';
const sample = `
<html><head><title>Story</title><link rel="stylesheet" href="/style.css"></head>
<body>
  <script>window.evil=1;</script>
  <div class="ai-overview">Google AI Overview here</div>
  <img src="https://files.oaiusercontent.com/pic.png" alt="a scene">
  <img src="/local/photo.jpg" alt="Made with AI by the newsroom">
  <img src="/local/art.jpg" alt="stunning ai art piece">
  <img src="/local/real.jpg" alt="a real photograph of a dog">
  <p>This article was generated by an automated system.</p>
  <p>A normal paragraph about local weather and traffic today downtown.</p>
  <a href="/next-page">Next</a>
  <a href="https://chatgpt.com/share/abc">an AI chat link</a>
</body></html>`;

const { html, counts } = filterHtml(sample, base);

// Scripts stripped
assert(!/window\.evil/.test(html), 'scripts should be removed');
// AI widget removed
assert(!/AI Overview here/.test(html), 'AI widget should be removed');
// AI-source image blocked
assert(/AI media blocked/.test(html), 'AI media placeholder should appear');
assert(!/<img[^>]*oaiusercontent/.test(html), 'AI image element should be gone (reason text may still name the source)');
// AI-labeled image blocked (reason present)
assert(/Labeled as AI/.test(html), 'AI-labeled image should be blocked');
// Weak hint flagged, not blocked
assert(/Possibly AI/.test(html), 'weak-hint image should be flagged');
// Real photo untouched
assert(/real\.jpg/.test(html), 'real photo should survive');
// AI text disclosure banner
assert(/Possibly AI-written/.test(html), 'AI text should be flagged');
// Normal link rewritten through proxy, resolved to absolute
assert(/\/go\?url=https%3A%2F%2Fnews\.example\.com%2Fnext-page/.test(html), 'internal link should route through /go');
// AI link also routed through /go (will hit block page)
assert(/\/go\?url=https%3A%2F%2Fchatgpt\.com/.test(html), 'AI link should route through /go');
// Top bar injected
assert(/id="aiblockle-bar"/.test(html), 'top bar should be present');

// Site blocking + SSRF guard
assert(isBlockedSite('https://chatgpt.com/x') === true, 'chatgpt blocked');
assert(isBlockedSite('https://news.example.com') === false, 'news not blocked');
assert(isSafeTarget('http://localhost:3000') === false, 'localhost refused');
assert(isSafeTarget('https://10.0.0.5/') === false, 'private IP refused');
assert(isSafeTarget('https://example.com/') === true, 'public site allowed');
assert(isAiMediaHost('files.oaiusercontent.com') === 'oaiusercontent.com', 'ai media host detected');

console.log('counts:', counts);
console.log('ALL PROXY FILTER TESTS PASSED');
