// Runs inside every page the user visits (as the <webview> preload).
//
// Two jobs:
//   A) Hide AI *features* on pages (AI Overview, Copilot, Ask-AI, chatbots).
//   B) Detect AI *media and text* and either BLOCK it (confirmed) or add a
//      clear "Possibly AI" NOTICE (suspected) — every action states its reason.
//
// Honest limit: AI images/videos/text can't be reliably detected from the raw
// pixels/words. AIBlockle acts on checkable *signals* only — known AI sources,
// explicit "made with AI" labels, and self-disclosure in text — and always shows
// WHY, so you can validate each call yourself.
//
// Keep the lists below in sync with src/main/blocklist.js.

(function () {
  'use strict';

  // ---- Lists (mirrored from blocklist.js) --------------------------------

  const AI_KEYWORDS = [
    'ai overview', 'ai-generated', 'ai generated', 'generated by ai', 'ask ai',
    'ask copilot', 'ai assistant', 'ai chat', 'chat with ai', 'ai summary',
    'summarize with ai', 'ai answer', 'powered by ai', 'ai suggestions',
  ];

  const AI_ELEMENT_HINTS = [
    'ai-overview', 'ai-assistant', 'ai-chat', 'ai-widget', 'ai-summary',
    'ai-answer', 'ask-ai', 'copilot', 'chatbot', 'gen-ai', 'genai',
  ];

  const KNOWN_AI_SELECTORS = [
    '[data-attrid="AIOverview"]', 'div[aria-label="AI Overview"]',
    '#bard-container', '.ai-overview', '.copilot', '#b_sydConvContainer',
  ];

  const AI_MEDIA_DOMAINS = [
    'oaiusercontent.com', 'cdn.openai.com', 'cdn.midjourney.com',
    'replicate.delivery', 'pbxt.replicate.delivery', 'cdn.leonardo.ai',
    'ideogram.ai', 'krea.ai', 'fal.media', 'v3.fal.media', 'image.civitai.com',
    'imagecache.civitai.com', 'pollinations.ai', 'image.pollinations.ai',
    'stability.ai', 'clipdrop-api.co', 'cdn.runwayml.com',
  ];

  const STRONG_AI_LABELS = [
    'ai-generated', 'ai generated', 'generated by ai', 'generated with ai',
    'made with ai', 'created with ai', 'created using ai', 'ai-created',
    'synthetic media', 'deepfake', 'midjourney', 'dall-e', 'dall·e',
    'stable diffusion', 'generated image', 'sora ai', 'google veo',
    'runway gen', 'firefly (ai)', 'adobe firefly',
  ];

  const WEAK_AI_HINTS = [
    'ai art', 'ai image', 'ai photo', 'ai video', 'genai', 'gen-ai',
    'generative', 'prompt:', 'text-to-image', 'text to image', 'upscaled',
  ];

  const AI_TEXT_DISCLOSURES = [
    'this article was generated by', 'this article was written by ai',
    'generated by artificial intelligence', 'written with the help of ai',
    'written with ai', 'ai-generated content', 'this content was created using ai',
    'created with the assistance of ai', 'this summary was generated by',
    'automatically generated by ai', 'this text was generated', 'ai-assisted article',
  ];

  // ---- State + counters --------------------------------------------------

  const MARK = 'data-aiblockle';
  let blockedCount = 0;   // confirmed AI, removed/replaced
  let flaggedCount = 0;   // suspected AI, noticed
  let stylePill = null;

  // ---- Helpers -----------------------------------------------------------

  function containsAny(text, list) {
    for (const needle of list) {
      if (text.includes(needle)) return needle;
    }
    return null;
  }

  // Whole-word match, so "ai" doesn't fire inside "chair"/"detail".
  function matchesWeakHint(text) {
    for (const hint of WEAK_AI_HINTS) {
      const re = new RegExp('(^|[^a-z])' + escapeRe(hint) + '([^a-z]|$)', 'i');
      if (re.test(text)) return hint;
    }
    return null;
  }
  function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

  function hostOf(url) {
    try { return new URL(url, location.href).hostname.toLowerCase(); }
    catch { return ''; }
  }

  function hostMatchesAiMedia(host) {
    for (const d of AI_MEDIA_DOMAINS) {
      if (host === d || host.endsWith('.' + d)) return d;
    }
    return null;
  }

  // Gather text that describes a media element: alt, title, aria-label, filename,
  // and a nearby caption (<figcaption> or parent text).
  function mediaContext(el) {
    let ctx = [
      el.getAttribute && el.getAttribute('alt'),
      el.getAttribute && el.getAttribute('title'),
      el.getAttribute && el.getAttribute('aria-label'),
      el.currentSrc || el.src || '',
    ].filter(Boolean).join(' ');

    const fig = el.closest && el.closest('figure');
    if (fig) {
      const cap = fig.querySelector('figcaption');
      if (cap) ctx += ' ' + cap.textContent;
    }
    return ctx.toLowerCase();
  }

  // ---- Actions -----------------------------------------------------------

  function blockMedia(el, reason) {
    if (el.getAttribute(MARK)) return;
    el.setAttribute(MARK, 'blocked');
    blockedCount += 1;

    const rect = el.getBoundingClientRect();
    const w = Math.max(rect.width, 120);
    const h = Math.max(rect.height, 90);

    const box = document.createElement('div');
    box.className = 'aiblockle-blocked-box';
    box.style.width = w + 'px';
    box.style.height = h + 'px';
    box.innerHTML =
      '<div class="aiblockle-blocked-inner">' +
        '<div class="aiblockle-shield">🛡️</div>' +
        '<div class="aiblockle-title">AI media blocked</div>' +
        '<div class="aiblockle-reason"></div>' +
        '<button class="aiblockle-show">Show anyway</button>' +
      '</div>';
    box.querySelector('.aiblockle-reason').textContent = reason;

    box.querySelector('.aiblockle-show').addEventListener('click', (e) => {
      e.preventDefault();
      box.replaceWith(el);
      el.removeAttribute(MARK);
    });

    if (el.parentNode) el.parentNode.replaceChild(box, el);
    updatePill();
  }

  function noticeMedia(el, reason) {
    if (el.getAttribute(MARK)) return;
    el.setAttribute(MARK, 'flagged');
    flaggedCount += 1;

    // Wrap the media so we can pin a corner badge over it.
    const wrap = document.createElement('span');
    wrap.className = 'aiblockle-flag-wrap';
    const badge = document.createElement('span');
    badge.className = 'aiblockle-badge';
    badge.textContent = '⚠ Possibly AI';
    badge.title = 'AIBlockle flagged this as possibly AI.\nReason: ' + reason;

    if (el.parentNode) {
      el.parentNode.insertBefore(wrap, el);
      wrap.appendChild(el);
      wrap.appendChild(badge);
    }
    updatePill();
  }

  function noticeText(blockEl, reason) {
    if (blockEl.getAttribute(MARK)) return;
    blockEl.setAttribute(MARK, 'flagged-text');
    flaggedCount += 1;

    const banner = document.createElement('div');
    banner.className = 'aiblockle-text-banner';
    banner.innerHTML =
      '<span class="aiblockle-badge-inline">⚠ Possibly AI-written</span>' +
      '<span class="aiblockle-text-reason"></span>';
    banner.querySelector('.aiblockle-text-reason').textContent = reason;
    blockEl.parentNode && blockEl.parentNode.insertBefore(banner, blockEl);
    updatePill();
  }

  // ---- Scanners ----------------------------------------------------------

  function scanAiWidgets(root) {
    for (const sel of KNOWN_AI_SELECTORS) {
      let nodes = [];
      try { nodes = root.querySelectorAll(sel); } catch { continue; }
      nodes.forEach((el) => {
        if (el.getAttribute(MARK)) return;
        el.setAttribute(MARK, 'widget');
        el.style.setProperty('display', 'none', 'important');
        blockedCount += 1;
      });
    }
    let candidates = [];
    try { candidates = root.querySelectorAll('div,section,aside,iframe,button,a,span'); }
    catch { return; }
    for (const el of candidates) {
      if (el.getAttribute(MARK)) continue;
      let blob = ((el.id || '') + ' ' + (el.className && el.className.toString ? el.className.toString() : '')).toLowerCase();
      for (const a of el.attributes || []) {
        if (a.name.startsWith('data-') || a.name.startsWith('aria-') || a.name === 'role') {
          blob += ' ' + a.name + ' ' + a.value;
        }
      }
      if (containsAny(blob, AI_ELEMENT_HINTS)) {
        el.setAttribute(MARK, 'widget');
        el.style.setProperty('display', 'none', 'important');
        blockedCount += 1;
        continue;
      }
      const tag = el.tagName;
      if (tag === 'BUTTON' || tag === 'A' || tag === 'SPAN') {
        const t = (el.textContent || '').trim().toLowerCase();
        if (t && t.length <= 60 && containsAny(t, AI_KEYWORDS)) {
          el.setAttribute(MARK, 'widget');
          el.style.setProperty('display', 'none', 'important');
          blockedCount += 1;
        }
      }
    }
  }

  function scanMedia(root) {
    let media = [];
    try { media = root.querySelectorAll('img,video,picture source,video source'); }
    catch { return; }

    for (const el of media) {
      if (el.getAttribute(MARK)) continue;
      const target = el.tagName === 'SOURCE' ? (el.closest('picture,video') || el) : el;
      if (target.getAttribute && target.getAttribute(MARK)) continue;

      const src = el.currentSrc || el.src || el.getAttribute('src') || el.getAttribute('srcset') || '';
      const host = hostOf(src);
      const ctx = mediaContext(el);

      // CONFIRMED: served from a known AI generator.
      const aiHost = hostMatchesAiMedia(host);
      if (aiHost) { blockMedia(target, 'Loaded from a known AI image/video source (' + aiHost + ')'); continue; }

      // CONFIRMED: an explicit AI label on/near the media.
      const strong = containsAny(ctx, STRONG_AI_LABELS);
      if (strong) { blockMedia(target, 'Labeled as AI: “' + strong + '”'); continue; }

      // SUSPECTED: weaker AI hint -> notice, do not block.
      const weak = matchesWeakHint(ctx);
      if (weak) { noticeMedia(target, 'Contains AI hint: “' + weak + '”'); continue; }
    }
  }

  function scanText(root) {
    let blocks = [];
    try { blocks = root.querySelectorAll('article,p,section,blockquote,li'); }
    catch { return; }
    for (const el of blocks) {
      if (el.getAttribute(MARK)) continue;
      const t = (el.textContent || '').toLowerCase();
      if (t.length < 12 || t.length > 4000) continue;
      const hit = containsAny(t, AI_TEXT_DISCLOSURES);
      if (hit) noticeText(el, 'Text discloses AI authorship: “' + hit + '”');
    }
  }

  function scan(root) {
    if (!root || !root.querySelectorAll) return;
    scanAiWidgets(root);
    scanMedia(root);
    scanText(root);
  }

  // ---- Status pill (simple, always-visible validation) -------------------

  function ensurePill() {
    if (stylePill && document.body && document.body.contains(stylePill)) return;
    if (!document.body) return;
    stylePill = document.createElement('div');
    stylePill.className = 'aiblockle-pill';
    stylePill.title = 'AIBlockle is filtering this page.\n' +
      'Blocked = confirmed AI (removed). Flagged = possibly AI (marked, kept).';
    document.body.appendChild(stylePill);
    updatePill();
  }

  function updatePill() {
    if (!stylePill) return;
    stylePill.textContent = '🛡️ AIBlockle · ' + blockedCount + ' blocked · ' + flaggedCount + ' flagged';
    stylePill.style.display = (blockedCount + flaggedCount) > 0 ? 'block' : 'none';
  }

  // ---- Styles ------------------------------------------------------------

  function injectStyles() {
    if (document.getElementById('aiblockle-style')) return;
    const css = `
      .aiblockle-blocked-box{display:inline-flex;align-items:center;justify-content:center;
        background:repeating-linear-gradient(45deg,#1c2128,#1c2128 10px,#20262e 10px,#20262e 20px);
        border:1px solid #30363d;border-radius:10px;color:#e6e9ee;box-sizing:border-box;
        font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;vertical-align:middle;}
      .aiblockle-blocked-inner{text-align:center;padding:10px;max-width:100%;}
      .aiblockle-shield{font-size:26px;}
      .aiblockle-title{font-weight:600;font-size:13px;margin-top:4px;}
      .aiblockle-reason{font-size:11px;color:#9aa4b2;margin:4px 8px 0;line-height:1.35;}
      .aiblockle-show{margin-top:8px;font-size:11px;background:#30363d;color:#e6e9ee;border:none;
        border-radius:6px;padding:4px 10px;cursor:pointer;}
      .aiblockle-flag-wrap{position:relative;display:inline-block;}
      .aiblockle-badge{position:absolute;top:6px;left:6px;background:rgba(240,136,62,.95);color:#241300;
        font:600 11px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;padding:4px 7px;
        border-radius:6px;pointer-events:auto;cursor:help;z-index:2147483000;box-shadow:0 1px 4px rgba(0,0,0,.4);}
      .aiblockle-text-banner{display:flex;gap:8px;align-items:baseline;background:#2a1c0e;
        border-left:3px solid #f0883e;border-radius:6px;padding:6px 10px;margin:8px 0;
        font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;}
      .aiblockle-badge-inline{color:#f0883e;font-weight:600;font-size:12px;white-space:nowrap;}
      .aiblockle-text-reason{color:#c9b8a4;font-size:12px;}
      .aiblockle-pill{position:fixed;bottom:14px;left:14px;z-index:2147483600;background:#111418;
        color:#e6e9ee;border:1px solid #30363d;border-radius:20px;padding:7px 13px;font:600 12px/1
        -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;box-shadow:0 3px 10px rgba(0,0,0,.4);
        display:none;cursor:default;}
    `;
    const style = document.createElement('style');
    style.id = 'aiblockle-style';
    style.textContent = css;
    (document.head || document.documentElement).appendChild(style);
  }

  // ---- Boot --------------------------------------------------------------

  function run() {
    injectStyles();
    ensurePill();
    scan(document);
    updatePill();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', run, { once: true });
  } else {
    run();
  }

  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      for (const node of m.addedNodes) {
        if (node.nodeType === 1) scan(node);
      }
    }
    ensurePill();
    updatePill();
  });

  function startObserving() {
    if (document.documentElement) {
      observer.observe(document.documentElement, { childList: true, subtree: true });
    } else {
      document.addEventListener('DOMContentLoaded', startObserving, { once: true });
    }
  }
  startObserving();
})();
