// Runs inside every page the user visits (as the <webview> preload).
// It hides AI-related on-page features: Google's "AI Overview", Bing/Copilot
// panels, "Ask AI" buttons, embedded chatbots, and elements marked as AI.
//
// This is the DOM layer of AIBlockle. Network-level blocking (whole AI sites,
// AI API calls) happens in the main process; this handles AI features that ride
// along inside otherwise-normal pages.

(function () {
  'use strict';

  // Keep these in sync with src/main/blocklist.js. They're duplicated here
  // because the guest page runs in an isolated context without require().
  const AI_KEYWORDS = [
    'ai overview',
    'ai-generated',
    'ai generated',
    'generated by ai',
    'ask ai',
    'ask copilot',
    'ai assistant',
    'ai chat',
    'chat with ai',
    'ai summary',
    'summarize with ai',
    'ai answer',
    'powered by ai',
    'ai suggestions',
  ];

  const AI_ELEMENT_HINTS = [
    'ai-overview',
    'ai-assistant',
    'ai-chat',
    'ai-widget',
    'ai-summary',
    'ai-answer',
    'ask-ai',
    'copilot',
    'chatbot',
    'gen-ai',
    'genai',
  ];

  // Site-specific selectors for well-known AI panels that don't self-label
  // in a way the generic rules catch.
  const KNOWN_AI_SELECTORS = [
    '[data-attrid="AIOverview"]',        // Google AI Overview
    '[jsname][data-al-attr]',            // (guarded further below)
    'div[aria-label="AI Overview"]',
    '#bard-container',
    '.ai-overview',
    '.copilot',
    '#b_sydConvContainer',               // Bing Copilot container
  ];

  const HIDE_MARK = 'data-aiblockle-hidden';
  let hiddenCount = 0;

  function markHidden(el) {
    if (!el || el.getAttribute(HIDE_MARK)) return;
    el.setAttribute(HIDE_MARK, '1');
    el.style.setProperty('display', 'none', 'important');
    hiddenCount += 1;
  }

  function attrBlob(el) {
    // Collect class/id/aria/data-* text for hint matching.
    let blob = (el.id || '') + ' ' + (el.className && el.className.toString ? el.className.toString() : '');
    for (const attr of el.attributes || []) {
      if (attr.name.startsWith('data-') || attr.name.startsWith('aria-') || attr.name === 'role') {
        blob += ' ' + attr.name + ' ' + attr.value;
      }
    }
    return blob.toLowerCase();
  }

  function looksLikeAiContainer(el) {
    const blob = attrBlob(el);
    for (const hint of AI_ELEMENT_HINTS) {
      if (blob.includes(hint)) return true;
    }
    return false;
  }

  function textLabelsAi(el) {
    // Only treat short, label-like text as an AI marker, so we don't nuke
    // long articles that happen to discuss AI.
    const text = (el.textContent || '').trim().toLowerCase();
    if (text.length === 0 || text.length > 60) return false;
    for (const kw of AI_KEYWORDS) {
      if (text.includes(kw)) return true;
    }
    return false;
  }

  function scan(root) {
    if (!root || !root.querySelectorAll) return;

    // 1. Known AI panels.
    for (const sel of KNOWN_AI_SELECTORS) {
      let nodes = [];
      try {
        nodes = root.querySelectorAll(sel);
      } catch {
        continue;
      }
      nodes.forEach(markHidden);
    }

    // 2. Elements whose attributes mark them as AI containers.
    let candidates = [];
    try {
      candidates = root.querySelectorAll('div,section,aside,iframe,button,a,span');
    } catch {
      return;
    }
    for (const el of candidates) {
      if (el.getAttribute(HIDE_MARK)) continue;
      if (looksLikeAiContainer(el)) {
        markHidden(el);
        continue;
      }
      // 3. Buttons/links that are explicitly labeled as AI actions.
      const tag = el.tagName;
      if ((tag === 'BUTTON' || tag === 'A' || tag === 'SPAN') && textLabelsAi(el)) {
        markHidden(el);
      }
    }
  }

  function run() {
    scan(document);
    reportCount();
  }

  function reportCount() {
    try {
      // Surface the count to the toolbar via title channel is avoided;
      // instead expose it on window for optional debugging.
      window.__aiblockleHidden = hiddenCount;
    } catch {
      /* ignore */
    }
  }

  // Initial pass once DOM is ready.
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', run, { once: true });
  } else {
    run();
  }

  // Keep hiding AI panels that load in dynamically (SPAs, lazy widgets).
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      for (const node of m.addedNodes) {
        if (node.nodeType === 1) {
          scan(node);
        }
      }
    }
    reportCount();
  });

  function startObserving() {
    if (document.body) {
      observer.observe(document.documentElement, { childList: true, subtree: true });
    } else {
      document.addEventListener('DOMContentLoaded', startObserving, { once: true });
    }
  }
  startObserving();
})();
